RISC-V: testsuite: fix an obvious build error
For a non-multilib build, I see following errors.

| FAIL: gcc.target/riscv/rvv/vtype-call-clobbered.c (test for excess errors)
| Excess errors:
| TC-INSTxyz/sysroot/usr/include/gnu/stubs.h:14:11: fatal error: gnu/stubs-lp64.h: No such file or directory compilation terminated.

The test selects non default ABI lp64 (vs. lp64d) for no real reason.
Fix that.

gcc/testsuite/ChangeLog:

	* gcc.target/riscv/rvv/vtype-call-clobbered.c: Fix -mabi.

Signed-off-by: Vineet Gupta <vineetg@rivosinc.com>
(cherry picked from commit 0005b1e577135bf0345447529d138f4d15618ec0)